### ISSUE TITLE
What's the resolution of 3D grids to generate meshes?

### ISSUE THREAD

**Issue by zjwzcx** [PierreMarza/autonerf#4]
Hi Pierre, thanks for your awesome work! I'm curious about the resolution of 3D grids to generate mentioned NeRF-based meshes. Is it defined by voxel_size(1cm x 1cm x 1cm)?

**Comment by PierreMarza** [comment]
Hi, thank you for your interest in our work! 

Are you referring to the process to generate meshes from Semantic NeRF (https://github.com/PierreMarza/autonerf/blob/main/semantic_nerf/SSR/extract_colour_mesh.py)? 

If that’s the case, we specify a “grid_dim” argument (default: 256) defining the dimensions of the voxel grid used to generate the mesh (e.g. 256*256*256 in the default setting). Then, we compute scene bounds from training data poses (adding some padding to avoid cropping the scene). The final resolution thus depends on the size of the scene and the grid_dim argument (e.g. if we consider the scene has length l along one axis, the axis resolution will be l/grid_dim).

Please let me know if this answers your question!

**Comment by zjwzcx** [comment]
> Hi, thank you for your interest in our work!
> 
> Are you referring to the process to generate meshes from Semantic NeRF (https://github.com/PierreMarza/autonerf/blob/main/semantic_nerf/SSR/extract_colour_mesh.py)?
> 
> If that’s the case, we specify a “grid_dim” argument (default: 256) defining the dimensions of the voxel grid used to generate the mesh (e.g. 256_256_256 in the default setting). Then, we compute scene bounds from training data poses (adding some padding to avoid cropping the scene). The final resolution thus depends on the size of the scene and the grid_dim argument (e.g. if we consider the scene has length l along one axis, the axis resolution will be l/grid_dim).
> 
> Please let me know if this answers your question!

Thanks for your prompt and useful reply! :)
